version: '3.9'

networks:
  InceptionNetowrk:
    driver: bridge

volumes:
  data_word:
    driver_opts:
      type: none
      o: bind
      device: /home/med/data/wordpress


services:
  nginx:
    build: ./requirement/nginx
    container_name: nginx
    ports:
      - '443:443'
    volumes:
      - data_word:/var/www/wordpress
    networks:
      - InceptionNetowrk
    depends_on:
      - wordpress

  wordpress:
    build: ./requirement/wordpress
    container_name: wordpress
    ports:
      - '9000:9000'
    networks:
      - InceptionNetowrk
    volumes:
      - data_word:/var/wordpress